"""empty message

Revision ID: 164e64ea79b0
Revises: 5e799e54ff49
Create Date: 2021-05-31 09:55:14.231468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164e64ea79b0'
down_revision = '5e799e54ff49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat', ['id'])
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_unique_constraint(None, 'message', ['id'])
    op.create_unique_constraint(None, 'post', ['id'])
    op.create_unique_constraint(None, 'share_trip', ['id'])
    op.create_unique_constraint(None, 'trip', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'trip', type_='unique')
    op.drop_constraint(None, 'share_trip', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_constraint(None, 'chat', type_='unique')
    # ### end Alembic commands ###
