"""empty message

Revision ID: 39f381517b01
Revises: 4e85be72fa5d
Create Date: 2021-05-28 10:34:51.357224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f381517b01'
down_revision = '4e85be72fa5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat', ['id'])
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_unique_constraint(None, 'message', ['id'])
    op.create_unique_constraint(None, 'post', ['id'])
    op.create_unique_constraint(None, 'share_trip', ['id'])
    op.create_unique_constraint(None, 'trip', ['id'])
    op.add_column('user', sa.Column('_password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', '_password')
    op.drop_constraint(None, 'trip', type_='unique')
    op.drop_constraint(None, 'share_trip', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_constraint(None, 'chat', type_='unique')
    # ### end Alembic commands ###
