"""empty message

Revision ID: 411c8c6506f9
Revises: 44f82b044994
Create Date: 2021-06-16 08:36:51.017385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411c8c6506f9'
down_revision = '44f82b044994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('share_trip')
    op.create_unique_constraint(None, 'chat', ['id'])
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_unique_constraint(None, 'message', ['id'])
    op.create_unique_constraint(None, 'post', ['id'])
    op.create_unique_constraint(None, 'traveler', ['id'])
    op.create_unique_constraint(None, 'trip', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='unique')
    op.drop_constraint(None, 'traveler', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_constraint(None, 'chat', type_='unique')
    op.create_table('share_trip',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('traveler_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler.id'], name='share_trip_traveler_id_fkey'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name='share_trip_trip_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='share_trip_pkey')
    )
    op.drop_table('shared_trip')
    # ### end Alembic commands ###
