"""empty message

Revision ID: 5bd1d53256e2
Revises: 73776097697c
Create Date: 2021-07-02 08:55:12.841010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd1d53256e2'
down_revision = '73776097697c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post', ['id'])
    op.create_unique_constraint(None, 'shared_trip', ['id'])
    op.create_unique_constraint(None, 'traveler', ['id'])
    op.create_unique_constraint(None, 'trip', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='unique')
    op.drop_constraint(None, 'traveler', type_='unique')
    op.drop_constraint(None, 'shared_trip', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    # ### end Alembic commands ###
