"""empty message

Revision ID: 956c249fb404
Revises: fec3e3346a2f
Create Date: 2021-05-28 14:36:34.218588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956c249fb404'
down_revision = 'fec3e3346a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(), nullable=True))
    op.drop_column('user', 'languages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('languages', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'language')
    # ### end Alembic commands ###
