"""empty message

Revision ID: e61f49bcfb26
Revises: 39f381517b01
Create Date: 2021-05-28 12:51:48.399186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61f49bcfb26'
down_revision = '39f381517b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('user', 'mail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
