"""empty message

Revision ID: fec3e3346a2f
Revises: e61f49bcfb26
Create Date: 2021-05-28 14:34:48.488423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec3e3346a2f'
down_revision = 'e61f49bcfb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('languages', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'languages')
    # ### end Alembic commands ###
